Repository endojs/endo, pull requests merged in 2021-08, with the labels that each got.

#858 feat: delegate linting to the `@jessie.js/eslint-plugin`
  packages/eslint-config/eslint-config.json
  packages/eslint-config/package.json
  packages/eslint-plugin/README.md
  packages/eslint-plugin/lib/configs/recommended.js
  packages/eslint-plugin/lib/index.js
  packages/eslint-plugin/lib/processors/use-jessie.js
  yarn.lock
Labels: enhancement

#846 refactor(ses): Freeze proxy handlers for scopes
  packages/ses/src/scope-handler.js
Labels: audit-sestival

#817 Add tests for backslash behavior
  packages/ses/test/test-backslash-u-identifier.js
Labels: security, audit-sestival

#827 Lint to disallow SES polymorphic calls
  packages/eslint-plugin/lib/rules/no-polymorphic-call.js
  packages/ses/index.js
  packages/ses/package.json
  packages/ses/src/commons.js
  packages/ses/src/compartment-evaluate.js
  packages/ses/src/compartment-shim.js
  packages/ses/src/enable-property-overrides.js
  packages/ses/src/error/assert.js
  packages/ses/src/error/console.js
  packages/ses/src/error/fatal-assert.js
  packages/ses/src/error/stringify-utils.js
  packages/ses/src/error/tame-console.js
  packages/ses/src/error/tame-error-constructor.js
  packages/ses/src/error/tame-v8-error-constructor.js
  packages/ses/src/evaluate.js
  packages/ses/src/get-anonymous-intrinsics.js
  packages/ses/src/get-source-url.js
  packages/ses/src/intrinsics.js
  packages/ses/src/lockdown-shim.js
  packages/ses/src/module-instance.js
  packages/ses/src/module-link.js
  packages/ses/src/module-load.js
  packages/ses/src/module-proxy.js
  packages/ses/src/scope-constants.js
  packages/ses/src/scope-handler.js
  packages/ses/src/tame-date-constructor.js
  packages/ses/src/tame-function-constructors.js
  packages/ses/src/tame-locale-methods.js
  packages/ses/src/tame-math-object.js
  packages/ses/src/tame-regexp-constructor.js
  packages/ses/src/transforms.js
  packages/ses/src/whitelist-intrinsics.js
Labels: audit-sestival
