Repository endojs/endo, pull requests merged in 2021-07, with the labels that each got.

#811 ci: deploy netlify site to redirect to the demos page
  packages/ses/_redirects
  packages/ses/demos/challenge/README.md
  packages/ses/demos/challenge/index.html
Labels: documentation

#813 refactor(ses): Clarify markVirtualizedNativeFunction
  packages/ses/index.js
  packages/ses/src/commons.js
  packages/ses/src/compartment-shim.js
  packages/ses/src/global-object.js
  packages/ses/src/lockdown-shim.js
  packages/ses/src/tame-function-tostring.js
  packages/ses/src/whitelist-intrinsics.js
  packages/ses/test/test-global-object.js
Labels: audit-sestival

#824 fix!: Allow Map to be named in module scope
  packages/compartment-mapper/NEWS.md
  packages/compartment-mapper/src/bundle.js
  packages/ses/NEWS.md
  packages/ses/src/module-instance.js
  packages/static-module-record/NEWS.md
  packages/static-module-record/src/transform-analyze.js
  packages/static-module-record/test/test-static-module-record.js
Labels: audit-sestival

#831 refactor(ses): Add TODO #815 Just one makeCompartmentConstructor
  packages/ses/src/lockdown-shim.js
Labels: audit-least-authority

#838 docs(ses): Add an up reference to --proto-- in SES permits
  packages/ses/src/whitelist.js
Labels: audit-sestival

#830 refactor(ses): Add TODO #814 Once-only lockdown
  packages/ses/src/lockdown-shim.js
Labels: audit-sestival

#832 refactor(ses): Add TODO #816 Strict mode optimizer evaluation
  packages/ses/src/make-evaluate-factory.js
Labels: audit-sestival

#829 fix(ses): Defend integrity of intrinsics
  packages/ses/index.js
  packages/ses/package.json
  packages/ses/src/commons.js
  packages/ses/src/compartment-shim.js
  packages/ses/src/enable-property-overrides.js
  packages/ses/src/error/assert.js
  packages/ses/src/error/console.js
  packages/ses/src/error/stringify-utils.js
  packages/ses/src/error/tame-console.js
  packages/ses/src/error/tame-error-constructor.js
  packages/ses/src/error/tame-v8-error-constructor.js
  packages/ses/src/evaluate.js
  packages/ses/src/get-anonymous-intrinsics.js
  packages/ses/src/get-source-url.js
  packages/ses/src/intrinsics.js
  packages/ses/src/lockdown-shim.js
  packages/ses/src/make-evaluate-factory.js
  packages/ses/src/make-function-constructor.js
  packages/ses/src/make-hardener.js
  packages/ses/src/module-instance.js
  packages/ses/src/module-link.js
  packages/ses/src/module-load.js
  packages/ses/src/module-proxy.js
  packages/ses/src/scope-constants.js
  packages/ses/src/scope-handler.js
  packages/ses/src/tame-date-constructor.js
  packages/ses/src/tame-function-constructors.js
  packages/ses/src/tame-function-tostring.js
  packages/ses/src/tame-locale-methods.js
  packages/ses/src/tame-math-object.js
  packages/ses/src/tame-regexp-constructor.js
  packages/ses/src/transforms.js
  packages/ses/src/whitelist-intrinsics.js
  packages/ses/src/whitelist.js
Labels: audit-sestival

#833 refactor(ses): Avoid use of receiver object `this` in scope handler
  packages/ses/src/evaluate.js
  packages/ses/src/make-evaluate-factory.js
  packages/ses/src/scope-handler.js
  packages/ses/test/test-scope-handler.js
Labels: audit-sestival

#834 fix(ses): Scope proxy defense against property descriptor prototype
  packages/ses/src/scope-handler.js
  packages/ses/test/test-scope-handler-pollution.js
Labels: audit-sestival

#836 refactor(ses): Clarify internal terms for culling disallowed intrinsics
  packages/ses/src/whitelist-intrinsics.js
Labels: audit-sestival

#837 fix(ses): Use eslint-disable notation consistently
  packages/ses/src/module-link.js
  packages/ses/test/test-get-source-url.js
  packages/ses/test/test-property-override.js
Labels: audit-sestival

#810 docs(ses): Clarify motivation, fix links
  packages/ses/README.md
  packages/ses/demos/challenge/README.md
  packages/ses/docs/source/api.md
  packages/ses/docs/source/api.rst
  packages/ses/docs/source/getting-started.md
  packages/ses/docs/source/getting-started.rst
  packages/static-module-record/README.md
Labels: documentation
