Repository endojs/endo, pull requests merged in 2021-03, with the labels that each got.

#555 Wrap ava test function to log failures to actual console
  package.json
  packages/ses-ava/.prettierrc.json
  packages/ses-ava/LICENSE
  packages/ses-ava/NEWS.md
  packages/ses-ava/README.md
  packages/ses-ava/exported.js
  packages/ses-ava/jsconfig.json
  packages/ses-ava/package.json
  packages/ses-ava/rollup.config.js
  packages/ses-ava/src/main.js
  packages/ses-ava/src/ses-ava-test.js
  packages/ses-ava/src/types.js
  packages/ses-ava/test/test-raw-ava-reject.js
  packages/ses-ava/test/test-raw-ava-throw.js
  packages/ses-ava/test/test-ses-ava-reject.js
  packages/ses-ava/test/test-ses-ava-throw.js
Labels: debugging support

#610 docs: update description of the SES challenge to match reality
  packages/ses/demos/challenge/index.html
  packages/ses/demos/challenge/main.js
Labels: documentation

#641 Support Ava "macros" in ses-ava
  packages/ses-ava/src/ses-ava-test.js
  packages/ses-ava/src/types.js
Labels: bug, debugging support, enhancement
