Repository endojs/endo, pull requests merged in 2022-03, with the labels that each got.

#1096 Recast begone!
  packages/bundle-source/package.json
  packages/bundle-source/src/index.js
  packages/static-module-record/package.json
  packages/static-module-record/src/transform-analyze.js
  yarn.lock
Labels: bug

#1094 feat(hash-bundle): Create bundler hashing package
  package.json
  packages/bundle-source/NEWS.md
  packages/bundle-source/demo/integrity.js
  packages/bundle-source/package.json
  packages/bundle-source/src/index.js
  packages/bundle-source/test/snapshots/test-integrity.js.md
  packages/bundle-source/test/snapshots/test-integrity.js.snap
  packages/bundle-source/test/test-integrity.js
  packages/check-bundle/LICENSE
  packages/check-bundle/NEWS.md
  packages/check-bundle/README.md
  packages/check-bundle/SECURITY.md
  packages/check-bundle/index.js
  packages/check-bundle/jsconfig.json
  packages/check-bundle/lite.js
  packages/check-bundle/package.json
  packages/check-bundle/src/json.js
  packages/check-bundle/test/fixture/main.js
  packages/check-bundle/test/fixture/package.json
  packages/check-bundle/test/test-check-bundle.js
  packages/compartment-mapper/NEWS.md
  packages/compartment-mapper/archive.js
  packages/compartment-mapper/index.d.ts
  packages/compartment-mapper/index.js
  packages/compartment-mapper/src/archive.js
  packages/compartment-mapper/test/test-integrity.js
Labels: security, endo

#1095 fix(eventual-send): stronger (compatible) typing of `E` and `Remote`
  packages/eventual-send/jsconfig.test.json
  packages/eventual-send/package.json
  packages/eventual-send/src/E.js
  packages/eventual-send/src/index.d.ts
  packages/eventual-send/test/prepare-test-env-ava.js
  packages/eventual-send/test/test-types.js
  packages/far/src/index.js
  packages/marshal/src/make-far.js
Labels: enhancement

#1109 fix(static-module-record): use `Object.create(null)` to prevent crashes
  packages/static-module-record/src/transform-analyze.js
  packages/static-module-record/test/test-static-module-record.js
Labels: bug

#1107 fix(check-bundle): Immutable bundles and conveniences
  packages/check-bundle/NEWS.md
  packages/check-bundle/index.js
  packages/check-bundle/lite.js
  packages/check-bundle/test/fixture.json
  packages/check-bundle/test/test-check-bundle.js
Labels: security

#1114 fix(ses): Handle well-known symbol look-alikes
  packages/ses/src/commons.js
  packages/ses/src/whitelist-intrinsics.js
  packages/ses/src/whitelist.js
  packages/ses/test/test-repair-intrinsics.js
  packages/ses/test/test-whitelist-intrinsics.js
Labels: ses

#1115 Handle symbols installed on Promise by Node's `async_hooks`
  .github/workflows/ci.yml
  packages/init/jsconfig.json
  packages/init/package.json
  packages/init/pre-bundle-source.js
  packages/init/pre-remoting.js
  packages/init/pre.js
  packages/init/src/node-async_hooks-patch.js
  packages/init/src/node-async_hooks.js
  packages/init/src/pre-node.js
  packages/init/test/.eslintrc.json
  packages/init/test/fixture/ses-boot.js
  packages/init/test/test-async_hooks.js
  packages/init/test/test-bundle.js
  packages/ses/src/whitelist.js
Labels: endo, ses
