Repository endojs/endo, pull requests merged in 2022-02, with the labels that each got.

#1028 feat(stream)!: Protect streams against reentrance
  packages/stream/index.js
Labels: security

#1051 build: repoint `yarn.lock` at slimmer package of recast for TS
  yarn.lock
Labels: technical-debt

#1043 Update TypeScript to 4.5
  package.json
  packages/base64/package.json
  packages/cjs-module-analyzer/package.json
  packages/cli/package.json
  packages/compartment-mapper/package.json
  packages/daemon/package.json
  packages/eslint-config/package.json
  packages/eventual-send/src/handled-promise.js
  packages/lp32/package.json
  packages/marshal/src/dot-membrane.js
  packages/marshal/src/marshal-justin.js
  packages/marshal/src/marshal.js
  packages/marshal/src/passStyleOf.js
  packages/netstring/package.json
  packages/promise-kit/package.json
  packages/ses-ava/package.json
  packages/ses-types-test/package.json
  packages/ses/package.json
  packages/static-module-record/package.json
  packages/stream-node/package.json
  packages/stream-types-test/package.json
  packages/stream/package.json
  packages/syrup/package.json
  packages/where/package.json
  packages/zip/package.json
  scripts/repackage.sh
  yarn.lock
Labels: tooling

#1062 fix(nat): declare `allegedNum` as `unknown`, then assert
  packages/nat/src/index.js
Labels: enhancement

#1077 Adds some missing hardens
  packages/bundle-source/src/index.js
  packages/import-bundle/test/test-import-bundle.js
Labels: security-integrity
