Repository endojs/endo, pull requests merged in 2023-07, with the labels that each got.

#1667 fix(eventual-send): propagate `ERef<EOnly<R>>` to `EOnly` returns
  packages/eventual-send/src/E.js
  packages/eventual-send/src/types.d.ts
Labels: bug

#1679 docs(marshal): prune ibid
  packages/marshal/README.md
Labels: documentation

#1690 chore(eventual-send): standardize TS/JSDoc typing
  .prettierignore
  package.json
  packages/eslint-plugin/lib/configs/internal.js
  packages/eslint-plugin/package.json
  packages/eventual-send/package.json
  packages/eventual-send/shim.js
  packages/eventual-send/src/exports.d.ts
  packages/eventual-send/src/exports.js
  packages/eventual-send/src/exports.test-d.ts
  packages/eventual-send/src/handled-promise.js
  packages/eventual-send/src/no-shim.js
  packages/eventual-send/test/test-types.js
  yarn.lock
Labels: enhancement
