Repository endojs/endo, pull requests merged in 2024-07, with the labels that each got.

#2332 feat(evasive-transform): expose evadeCensorSync
  packages/evasive-transform/package.json
  packages/evasive-transform/src/index.js
  packages/evasive-transform/src/location-unmapper.js
  packages/evasive-transform/src/transform-ast.js
  packages/evasive-transform/test/evade-censor.test.js
  packages/evasive-transform/test/location-unmapper.test.js
  yarn.lock
Labels: enhancement

#2341 refactor(marshal,pass-style): #1687 move deeplyFulfilled to @endo/pas…
  packages/marshal/NEWS.md
  packages/marshal/index.js
  packages/pass-style/NEWS.md
  packages/pass-style/index.js
  packages/pass-style/src/deeplyFulfilled.js
  packages/pass-style/test/deeplyFulfilled.test.js
Labels: technical-debt

#2379 fix(bundle-source): Recognize default metadata
  packages/bundle-source/cache.js
  packages/bundle-source/src/bundle-source.js
  packages/bundle-source/test/cache.test.js
Labels: next-release

#2377 feat(import-bundle): accept symbol-named properties on inescapableGlobalProperties
  packages/import-bundle/NEWS.md
  packages/import-bundle/src/compartment-wrapper.js
  packages/import-bundle/src/compartment-wrapper.md
  packages/import-bundle/test/compartment-wrapper.test.js
Labels: next-release

#2374 chore(compartment-mapper): Restore backward compatibility for search
  packages/compartment-mapper/src/bundle.js
  packages/compartment-mapper/src/node-modules.js
  packages/compartment-mapper/src/search.js
  packages/compartment-mapper/test/search.test.js
Labels: next-release

#2387 harden-exports error on 'function' keyword
  packages/eslint-plugin/lib/rules/harden-exports.js
  packages/eslint-plugin/test/harden-exports.test.js
Labels: next-release

#2385 feat(ses): permit toHex etc
  packages/ses/src/permits.js
Labels: next-release

#2386 feat(ses): Compartment options migration
  packages/compartment-mapper/src/import-archive-lite.js
  packages/compartment-mapper/src/link.js
  packages/compartment-mapper/test/bundle.test.js
  packages/compartment-mapper/test/main.test.js
  packages/ses/NEWS.md
  packages/ses/README.md
  packages/ses/src/compartment.js
  packages/ses/src/error/assert.js
  packages/ses/test/compartment-constructor.test.js
  packages/ses/test/compartment-transforms.test.js
  packages/ses/test/compartment.test.js
  packages/ses/test/confinement.test.js
  packages/ses/test/error/tame-console-unfilteredError.test.js
  packages/ses/test/error/tame-console-unsafe-unfilteredError.test.js
  packages/ses/test/error/tame-console-unsafe-unsafeError-unfilteredError.test.js
  packages/ses/test/error/tame-console-unsafe-unsafeError.test.js
  packages/ses/test/error/tame-console-unsafe.test.js
  packages/ses/test/error/tame-console-unsafeError.test.js
  packages/ses/test/error/tame-console.test.js
  packages/ses/test/error/tame-v8-error-unsafe.test.js
  packages/ses/test/global-lexicals-evaluate.test.js
  packages/ses/test/global-object-mutability.test.js
  packages/ses/test/import-cjs.test.js
  packages/ses/test/import-gauntlet.test.js
  packages/ses/test/import-hook.test.js
  packages/ses/test/import-non-esm.test.js
  packages/ses/test/import-now-hook.test.js
  packages/ses/test/import-stack-traces.test.js
  packages/ses/test/import.test.js
  packages/ses/test/lockdown-compartment.test.js
  packages/ses/test/module-map-hook.test.js
  packages/ses/test/module-map.test.js
  packages/ses/test/ses.test.js
  packages/ses/types.d.ts
Labels: next-release

#2389 chore: Revert compartment-map.json tags to conditions schema migration
  packages/bundle-source/cache.js
  packages/bundle-source/src/zip-base64.js
  packages/compartment-mapper/README.md
  packages/compartment-mapper/src/archive-lite.js
  packages/compartment-mapper/src/bundle.js
  packages/compartment-mapper/src/capture-lite.js
  packages/compartment-mapper/src/compartment-map.js
  packages/compartment-mapper/src/node-modules.js
  packages/compartment-mapper/src/types.js
  packages/compartment-mapper/test/app.agar
Labels: next-release
