Repository endojs/endo, pull requests merged in 2024-08, with the labels that each got.

#2402 feat(ses): `errorTrapping` reports prepend `"SES_UNCAUGHT_EXCEPTION:"`
  packages/ses/NEWS.md
  packages/ses/error-codes/SES_ALREADY_LOCKED_DOWN.md
  packages/ses/error-codes/SES_UNCAUGHT_EXCEPTION.md
  packages/ses/error-codes/SES_UNHANDLED_REJECTION.md
  packages/ses/src/error/tame-console.js
  packages/ses/test/console-error-trap.test.js
  packages/ses/test/console-rejection-trap.test.js
Labels: ses

#2416 chore: `yarn up 'ses@workspace:^' '@endo/*@workspace:^'`
  lerna.json
  package.json
  packages/bundle-source/package.json
  packages/captp/package.json
  packages/check-bundle/package.json
  packages/cli/package.json
  packages/common/package.json
  packages/compartment-mapper/package.json
  packages/daemon/package.json
  packages/errors/package.json
  packages/evasive-transform/package.json
  packages/eventual-send/package.json
  packages/exo/package.json
  packages/far/package.json
  packages/import-bundle/package.json
  packages/init/package.json
  packages/lockdown/package.json
  packages/lp32/package.json
  packages/marshal/package.json
  packages/memoize/package.json
  packages/module-source/package.json
  packages/nat/package.json
  packages/netstring/package.json
  packages/pass-style/package.json
  packages/patterns/package.json
  packages/promise-kit/package.json
  packages/ses-ava/package.json
  packages/ses/package.json
  packages/skel/package.json
  packages/stream-node/package.json
  packages/stream-types-test/package.json
  packages/stream/package.json
  packages/test262-runner/package.json
  yarn.lock
Labels: technical-debt

#2427 feat(captp): handle `send` rejections
  packages/captp/NEWS.md
  packages/captp/src/captp.js
Labels: bug, enhancement

#2419 fix: Delete obsolete platform-compatibility-test
  .github/workflows/ci.yml
  packages/ses/package.json
Labels: next-release

#2398 feat(import-bundle): Support endoScript
  packages/import-bundle/NEWS.md
  packages/import-bundle/README.md
  packages/import-bundle/src/index.js
  packages/import-bundle/test/import-bundle.test.js
Labels: next-release
