Repository endojs/endo, pull requests merged in 2024-05, with the labels that each got.

#2262 docs(ses): more links for stack own accessor problem
  packages/ses/error-codes/SES_UNEXPECTED_ERROR_OWN_STACK_ACCESSOR.md
Labels: next-release

#2260 fix(ses): fix broken types for CJS consumers
  packages/ses/NEWS.md
  packages/ses/package.json
  packages/ses/package.json.md
  packages/ses/scripts/bundle.js
Labels: bug, next-release, ecosystem-compatibility

#2266 feat(pass-style,exo): exo boundary only throws throwables
  packages/exo/NEWS.md
  packages/exo/src/exo-tools.js
  packages/exo/test/test-exo-only-throwables.js
  packages/pass-style/NEWS.md
  packages/pass-style/index.js
  packages/pass-style/src/passStyleOf.js
  packages/pass-style/test/test-errors.js
Labels: next-release

#2297 chore: remove invalid prettier cfg from package.json
  packages/env-options/package.json
  packages/evasive-transform/package.json
  packages/memoize/package.json
Labels: tooling
