Repository endojs/endo, pull requests merged in 2024-11, with the labels that each got.

#2610 fix(compartment-mapper): Defer all importHook errors when importing a…
  packages/compartment-mapper/NEWS.md
  packages/compartment-mapper/src/import-hook.js
  packages/compartment-mapper/test/cjs-compat.test.js
Labels: bug

#2620 fix(compartment-mapper): top-level "this" is "module.exports"
  packages/compartment-mapper/src/parse-cjs.js
  packages/compartment-mapper/src/parse-pre-cjs.js
  packages/compartment-mapper/test/dynamic-require.test.js
  packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/app/index.js
  packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/exports-shenanigans/exports-this.js
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/static-app/README.md
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/static-app/index.js
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/static-app/package.json
  packages/compartment-mapper/test/snapshots/error-handling.test.js.md
  packages/compartment-mapper/test/snapshots/error-handling.test.js.snap
Labels: bug

#2624 fix(ses): fix #2598 with cauterizeProperty reuse
  packages/ses/src/cauterize-property.js
  packages/ses/src/compartment-shim.js
  packages/ses/src/intrinsics.js
  packages/ses/src/lockdown.js
  packages/ses/src/permits-intrinsics.js
  packages/ses/test/tolerate-empty-prototype-toplevel.test.js
  packages/ses/test/tolerate-empty-prototype.test.js
Labels: next-release

#2644 fix(ses): widen type of globalThis in Compartment
  packages/ses/types.d.ts
Labels: ses
