Repository endojs/endo, pull requests merged in 2025-07, with the labels that each got.

#2873 feat(marshal,patterns): env-option to config string order
  packages/marshal/NEWS.md
  packages/marshal/index.js
  packages/marshal/package.json
  packages/marshal/src/rankOrder.js
  packages/marshal/test/encodePassable-for-testing.js
  packages/marshal/test/encodePassable.test.js
  packages/marshal/test/marshal-capdata.test.js
  packages/marshal/test/marshal-justin.test.js
  packages/marshal/test/marshal-smallcaps.test.js
  packages/marshal/test/marshal-stringify.test.js
  packages/marshal/test/rankOrder.test.js
  packages/marshal/test/string-rank-both-order.test.js
  packages/marshal/test/string-rank-unicode-order.test.js
  packages/marshal/test/string-rank-utf16-order.test.js
  packages/marshal/tools/marshal-test-data.js
  packages/marshal/tools/prepare-error-if-order-choice-matters.js
  packages/marshal/tools/prepare-unicode-code-point-order.js
  packages/marshal/tools/prepare-utf16-code-unit-order.js
  packages/patterns/NEWS.md
  packages/patterns/test/string-key-unicode-order.test.js
  yarn.lock
Labels: ocapn

#2880 refactor: `hasOwn` rather than `hasOwnPropertyOf` or `objectHasOwnProperty`
  packages/exo/src/exo-tools.js
  packages/marshal/src/encodeToCapData.js
  packages/marshal/src/encodeToSmallcaps.js
  packages/marshal/src/marshal.js
  packages/pass-style/src/passStyle-helpers.js
  packages/pass-style/src/remotable.js
  packages/pass-style/src/safe-promise.js
  packages/patterns/src/patterns/patternMatchers.js
  packages/ses/src/cauterize-property.js
  packages/ses/src/commons.js
  packages/ses/src/enable-property-overrides.js
  packages/ses/src/error/assert.js
  packages/ses/src/global-object.js
  packages/ses/src/intrinsics.js
  packages/ses/src/make-hardener.js
  packages/ses/src/permits-intrinsics.js
  packages/ses/src/scope-constants.js
  packages/ses/src/tame-regenerator-runtime.js
Labels: technical-debt

#2822 feat(cache-map): Promote makeLRUCacheMap into a new package
  packages/cache-map/CHANGELOG.md
  packages/cache-map/LICENSE
  packages/cache-map/NEWS.md
  packages/cache-map/README.md
  packages/cache-map/SECURITY.md
  packages/cache-map/index.js
  packages/cache-map/package.json
  packages/cache-map/src/cachemap.js
  packages/cache-map/test/index.test.js
  packages/cache-map/tsconfig.build.json
  packages/cache-map/tsconfig.json
  packages/cache-map/types.d.ts
  packages/ses/package.json
  packages/ses/src/error/note-log-args.js
  packages/ses/src/make-lru-cachemap.js
  packages/ses/test/lru-cache-map.test.js
  yarn.lock
Labels: next-release

#2909 fix(compartment-mapper): do not blast named default exports in CJS
  packages/compartment-mapper/src/parse-cjs-shared-export-wrapper.js
  packages/compartment-mapper/test/cjs-compat.test.js
  packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/app/index.js
  packages/compartment-mapper/test/fixtures-cjs-compat/node_modules/exports-shenanigans/default-exports.js
  packages/compartment-mapper/test/scaffold.js
  packages/compartment-mapper/test/test.types.d.ts
Labels: bug, ecosystem-compatibility
