Repository endojs/endo, pull requests merged in 2025-05, with the labels that each got.

#1538 feat(pass-style,marshal): ByteArray, a new binary Passable type
  packages/marshal/index.js
  packages/marshal/src/encodePassable.js
  packages/marshal/src/encodeToCapData.js
  packages/marshal/src/encodeToSmallcaps.js
  packages/marshal/src/rankOrder.js
  packages/marshal/test/encodePassable.test.js
  packages/marshal/test/marshal-stringify.test.js
  packages/pass-style/src/byteArray.js
  packages/pass-style/src/deeplyFulfilled.js
  packages/pass-style/src/passStyleOf.js
  packages/pass-style/src/typeGuards.js
  packages/pass-style/src/types.d.ts
  packages/pass-style/tools/arb-passable.js
  packages/patterns/src/keys/checkKey.js
  packages/patterns/src/keys/compareKeys.js
  packages/patterns/src/patterns/patternMatchers.js
  packages/patterns/src/types.js
Labels: ocapn

#2802 fix(module-source): allow defaults in destructuring assignments
  packages/module-source/src/babel-plugin.js
  packages/module-source/test/module-source.test.js
Labels: bug

#2804 fix(ses): avoid depth-first loading sequence in loadNow to prevent getting stuck in cycles
  packages/ses/src/module-load.js
  packages/ses/test/import-cjs.test.js
Labels: bug

#2790 chore(ci): workflow hygiene
  .github/workflows/ci.yml
Labels: tooling

#2826 fix(compartment-mapper): handle missing optional packages in dynamically-required modules
  packages/compartment-mapper/src/import-hook.js
  packages/compartment-mapper/src/link.js
  packages/compartment-mapper/src/types/internal.ts
  packages/compartment-mapper/test/dynamic-require.test.js
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-app/README.md
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-app/index.js
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-app/package.json
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-optional/README.md
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-optional/main.js
  packages/compartment-mapper/test/fixtures-dynamic/node_modules/missing-optional/package.json
Labels: bug
