Repository endojs/endo, pull requests merged in 2025-08, with the labels that each got.

#2932 chore(ses): fix vanilla build script output
  packages/ses/scripts/bundle.js
Labels: tooling, ses

#2934 fix(ses): to workaround #2908 use current console
  packages/ses/docs/lockdown.md
  packages/ses/src/reporting.js
  packages/ses/test/error/_throws-and-logs.js
Labels: ecosystem-compatibility

#2928 feat(errors): self censoring stack frames
  packages/common/apply-labeling-error.js
  packages/common/throw-labeled.js
  packages/errors/NEWS.md
  packages/errors/index.js
  packages/errors/package.json
  packages/errors/test/deep-send.test.js
  packages/errors/test/deep-stacks.test.js
  packages/eventual-send/test/deep-send.test.js
  packages/eventual-send/test/deep-stacks.test.js
  packages/pass-style/test/message-breakpoints-demo.test.js
  packages/pass-style/test/message-breakpoints.test.js
  packages/patterns/src/patterns/patternMatchers.js
  packages/patterns/test/_stack-filtering-concise.js
  packages/patterns/test/_stack-filtering-verbose.js
  packages/patterns/test/mismatch-stack-concise-demo.test.js
  packages/patterns/test/mismatch-stack-verbose-demo.test.js
  packages/ses/docs/lockdown.md
  packages/ses/src/error/tame-v8-error-constructor.js
  yarn.lock
Labels: debugging support
